Feedback tests
kislyakdmitry/Helpdesk pull request #11
Opened 2022-04-12 14:33 UTC by SvetilnikST

2022-04-12 15:16 UTC, kislyakdmitry requested changes

2022-04-12 15:16 UTC, kislyakdmitry commented on src/main/java/innowise/zuevsky/helpdesk/security/JwtTokenFilter.java
> +				if (authentication != null) {
if null?

2022-04-12 15:16 UTC, kislyakdmitry commented on src/main/java/innowise/zuevsky/helpdesk/service/FeedbackService.java
> +				.orElseThrow(() -> new FeedbackNotFoundException(feedbackId));
формат

2022-04-12 15:16 UTC, kislyakdmitry commented on src/test/java/innowise/zuevsky/helpdesk/service/TicketsServiceTest.java
> +		TicketOwnerNotBelongsToUserException exception = assertThrows(TicketOwnerNotBelongsToUserException.class,
[](https://www.baeldung.com/assertj-exception-assertion#1-using-assertthatthrownby)3.1. Using assertThatThrownBy()
Let's check if indexing an out of bounds item in a list raises an IndexOutOfBoundsException:

assertThatThrownBy(() -> {
    List<String> list = Arrays.asList("String one", "String two");
    list.get(2);
}).isInstanceOf(IndexOutOfBoundsException.class)
  .hasMessageContaining("Index: 2, Size: 2");
Notice how the code fragment that might throw an exception gets passed as a lambda expression.

Of course, we can leverage various standard AssertJ assertions here like:

.hasMessage("Index: %s, Size: %s", 2, 2)
.hasMessageStartingWith("Index: 2")
.hasMessageContaining("2")
.hasMessageEndingWith("Size: 2")
.hasMessageMatching("Index: \\d+, Size: \\d+")
.hasCauseInstanceOf(IOException.class)
.hasStackTraceContaining("java.io.IOException");

2022-04-13 09:57 UTC, SvetilnikST commented on src/main/java/innowise/zuevsky/helpdesk/dto/FeedbackSaveDto.java
> +	@ApiModelProperty(notes = "Rate in feedback from 1 to 5", example = "5")
fix

2022-04-13 09:57 UTC, SvetilnikST commented on src/main/java/innowise/zuevsky/helpdesk/security/JwtTokenFilter.java
> +				if (authentication != null) {
fix

2022-04-13 11:40 UTC, SvetilnikST commented on src/main/java/innowise/zuevsky/helpdesk/service/FeedbackService.java
> +				.orElseThrow(() -> new FeedbackNotFoundException(feedbackId));
fix

2022-04-13 12:20 UTC, kislyakdmitry approved these changes

2022-04-13 12:20 UTC, merged